Create TABLE IF NOT EXISTS RIDE_REQUEST (  
ride_loc_id int NOT NULL AUTO_INCREMENT,
dispatcher_id int,
Ride_date DateTime,
sts_id int,
RIDE_ID int,
DRIVER_ID int,
PRIMARY KEY (ride_loc_id),
FOREIGN KEY (sts_id) REFERENCES ride_status (sts_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (RIDE_ID) REFERENCES RIDE_HISTORY (RIDE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (dispatcher_id) REFERENCES DISPATCHER_DETAILS (dispatcher_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (DRIVER_ID) REFERENCES driver_details (DRIVER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);