CREATE TABLE IF NOT EXISTS USER_DETAILS (
  USER_ID int NOT NULL AUTO_INCREMENT,
  NAME varchar(20) NOT NULL,
  FIRST_NAME varchar(20),
  LAST_NAME varchar(20),
  MIDDLE_NAME varchar(20),
  IS_MAJOR boolean,
  EMAIL varchar(100) NOT NULL,
  PH_NUM varchar(15) DEFAULT NULL,
  IMAGE_Url varchar(20) DEFAULT NULL,
  EMAIL_VERIFIED varchar(20) DEFAULT NULL,
  PASSWORD varchar(100),
  PROVIDER int,
  PROVIDER_ID varchar(100),
  LATITUDE DECIMAL(10,8) NULL,
  LONGITUDE DECIMAL(11,8) NULL,
  PRIMARY KEY (user_id)
);

INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('1','Ajay Kumar', 'Ajay', 'Kumar','Ajaykumar@gmail.com','+919177067400','Ajaykumar@7400',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('2','Abhi Kumar', 'Abhi', 'Kumar','Abhikumar@gmail.com','+919177067401','Abhikumar@7401',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('3','Ram Kumar', 'Ram', 'Kumar','Ramkumar@gmail.com','+919122012012','Ramkumar@7402',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('4','Raj Kumar', 'Raj', 'Kumar','Rajkumar@gmail.com','+919177067403','Rajkumar@7403',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('5','Prashanth Kumar', 'Prashanth', 'Kumar','Prashanth@gmail.com','+919177067404','Prashanthkumar@7404',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('6','Rama Raj', 'Rama', 'Raj','Ramaraj@gmail.com','+919177067405','Ramaraj@7405',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('7','Raj Tharun', 'Raj', 'Tharun','Rajtharun@gmail.com','+919177067406','rajTharun@7406',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('8','Rakesh kumar', 'Rakesh', 'Kumar','Rakeshkumar@gmail.com','+919177067407','Rakesh@7407',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('9','Sai Raj', 'Sai', 'Raj','Sairaj@gmail.com','+919177067408','Sairaj@7408',true);
INSERT INTO USER_DETAILS(USER_ID,NAME, FIRST_NAME, LAST_NAME,EMAIL,PH_NUM,PASSWORD,IS_MAJOR) VALUES('10','Amith Raj', 'Amith', 'Raj','Amithraj@gmail.com','+919177067409','Amithraj@7409',true);



