CREATE TABLE IF NOT EXISTS PAYMENT_DETAILS (  
PAYMENT_ID int NOT NULL AUTO_INCREMENT,
DISTANCE float,
PRICE float,
payment_type varchar(20),
USER_ID int,
DRIVER_ID int,
CAR_ID int,
created_date date,
TOTAL_AMOUNT float,
PRIMARY KEY (PAYMENT_ID),
FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER_DETAILS (DRIVER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (CAR_ID) REFERENCES CAR_DETAILS (CAR_ID) ON DELETE CASCADE ON UPDATE CASCADE
);